name: claude-runner

on:
  issues:
    types: [opened, edited, labeled]
  # （任意）/rerunを使う場合はアンコメント
  # issue_comment:
  #   types: [created, edited]

permissions:
  contents: write        # ブランチ作成・コミット
  pull-requests: write   # PR作成・更新
  issues: write          # Issueコメント

env:
  PROVIDER: ${{ vars.PROVIDER || 'stub' }}
  ANTHROPIC_MODEL: claude-3-5-sonnet-20240620
  OPENAI_MODEL: gpt-4o-mini

jobs:
  run:
    # ← pushなど他イベント時は実行しない（“push 失敗”ノイズ対策）
    if: ${{ github.event_name == 'issues' && contains(join(github.event.issue.labels.*.name, ','), 'claude-code') }}
    runs-on: ubuntu-latest
    # 同一Issueの並列起動を抑止（任意）
    concurrency:
      group: issues-${{ github.event.issue.number }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: Run runner
        env:
          # PATがあれば優先、無ければ標準トークン
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN || github.token }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node scripts/run_claude.mjs
